INSERT OR IGNORE INTO `pages` (`slug`, `title_en`, `title_ka`, `content_en`, `content_ka`, `sort_order`, `created_at`, `updated_at`) VALUES
(
  'terms',
  'Terms of Service',
  'მომსახურების პირობები',
  '<h2>Terms of Service</h2><p>Last updated: March 2026</p><p>Please read these Terms of Service carefully before using the AG Legal website or engaging our legal services. By accessing or using our services, you agree to be bound by these terms.</p><h3>1. Services</h3><p>AG Legal provides professional legal services including corporate law, litigation, real estate, and advisory services. The information on this website does not constitute legal advice.</p><h3>2. Confidentiality</h3><p>All information shared with AG Legal in connection with a client engagement is treated as strictly confidential in accordance with applicable professional conduct rules and Georgian law.</p><h3>3. Intellectual Property</h3><p>All content on this website is the property of AG Legal and protected by applicable intellectual property laws. You may not reproduce or distribute any content without prior written permission.</p><h3>4. Limitation of Liability</h3><p>AG Legal shall not be liable for any indirect, incidental, or consequential damages arising from the use of this website beyond the scope of the applicable engagement agreement.</p><h3>5. Governing Law</h3><p>These Terms are governed by the laws of Georgia. Any disputes shall be subject to the exclusive jurisdiction of the courts of Tbilisi.</p><h3>6. Contact</h3><p>For questions about these terms, please contact us at our <a href="/contact">contact page</a>.</p>',
  '<h2>მომსახურების პირობები</h2><p>ბოლო განახლება: მარტი 2026</p><p>გთხოვთ, ყურადღებით წაიკითხოთ მომსახურების პირობები AG Legal-ის ვებსაიტის გამოყენებამდე. ჩვენი მომსახურებით სარგებლობით, თქვენ ეთანხმებით ამ პირობებს.</p><h3>1. მომსახურება</h3><p>AG Legal გთავაზობთ პროფესიონალურ იურიდიულ მომსახურებას, მათ შორის კორპორატიულ სამართალს, სამართალწარმოებას, უძრავ ქონებასა და საკონსულტაციო მომსახურებებს.</p><h3>2. კონფიდენციალურობა</h3><p>AG Legal-თან გაზიარებული ყველა ინფორმაცია მკაცრად კონფიდენციალურია პროფესიული ქცევის წესებისა და საქართველოს კანონმდებლობის შესაბამისად.</p><h3>3. ინტელექტუალური საკუთრება</h3><p>ამ ვებსაიტზე განთავსებული ყველა კონტენტი AG Legal-ის საკუთრებაა და დაცულია გამოყენებული ინტელექტუალური საკუთრების კანონებით.</p><h3>4. პასუხისმგებლობის შეზღუდვა</h3><p>AG Legal არ აგებს პასუხს ამ ვებსაიტის გამოყენებით გამოწვეული არაპირდაპირი ან შედეგობრივი ზიანისთვის.</p><h3>5. მარეგულირებელი სამართალი</h3><p>ეს პირობები რეგულირდება საქართველოს კანონმდებლობით. ნებისმიერი დავა ექვემდებარება თბილისის სასამართლოების კომპეტენციას.</p>',
  10,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'privacy',
  'Privacy Policy',
  'კონფიდენციალობის პოლიტიკა',
  '<h2>Privacy Policy</h2><p>Last updated: March 2026</p><p>AG Legal is committed to protecting your privacy. This policy explains how we collect, use, and safeguard your personal information.</p><h3>1. Information We Collect</h3><p>We may collect the following information:</p><ul><li>Contact information (name, email address, phone number)</li><li>Information provided in consultation requests or messages</li><li>Technical data such as IP address and browser type</li></ul><h3>2. How We Use Your Information</h3><p>We use collected information to respond to inquiries, provide legal services, send relevant updates with your consent, and improve our website.</p><h3>3. Data Sharing</h3><p>We do not sell or rent your personal information. We may share information with trusted partners who assist in delivering our services, subject to confidentiality agreements, or where required by law.</p><h3>4. Data Security</h3><p>We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, disclosure, or loss.</p><h3>5. Your Rights</h3><p>You have the right to access, correct, or request deletion of your personal data. To exercise these rights, contact us via our <a href="/contact">contact page</a>.</p><h3>6. Cookies</h3><p>Our website may use cookies to improve your browsing experience. You can control cookie settings through your browser preferences.</p>',
  '<h2>კონფიდენციალობის პოლიტიკა</h2><p>ბოლო განახლება: მარტი 2026</p><p>AG Legal ვალდებულია დაიცვას თქვენი კონფიდენციალობა. ეს პოლიტიკა განმარტავს, თუ როგორ ვაგროვებთ, ვიყენებთ და ვიცავთ თქვენს პერსონალურ ინფორმაციას.</p><h3>1. შეგროვებული ინფორმაცია</h3><p>შეიძლება შევაგროვოთ:</p><ul><li>საკონტაქტო ინფორმაცია (სახელი, ელ-ფოსტა, ტელეფონი)</li><li>კონსულტაციის მოთხოვნებში მოწოდებული ინფორმაცია</li><li>ტექნიკური მონაცემები, როგორიცაა IP მისამართი</li></ul><h3>2. ინფორმაციის გამოყენება</h3><p>შეგროვებულ ინფორმაციას ვიყენებთ შეკითხვებზე პასუხისთვის, მომსახურების გასაწევად და ვებსაიტის გასაუმჯობესებლად.</p><h3>3. მონაცემთა გაზიარება</h3><p>ჩვენ არ ვყიდით თქვენს პერსონალურ ინფორმაციას. შეიძლება გავუზიაროთ ინფორმაცია სანდო პარტნიორებს კონფიდენციალობის ხელშეკრულების პირობებში.</p><h3>4. მონაცემთა უსაფრთხოება</h3><p>ვახორციელებთ შესაბამის ზომებს თქვენი პერსონალური მონაცემების დასაცავად.</p><h3>5. თქვენი უფლებები</h3><p>გაქვთ თქვენს მონაცემებზე წვდომის, მათი გასწორების ან წაშლის მოთხოვნის უფლება. დაგვიკავშირდით ჩვენი <a href="/contact">საკონტაქტო გვერდის</a> მეშვეობით.</p>',
  20,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
);
